### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by raphzy001** [ashtrobe/memefi-godmode#1]
valid...Traceback (most recent call last):
  File "/data/data/com.termux/files/home/memefi-godmode/memefi.py", line 582, in <module>
    main()
  File "/data/data/com.termux/files/home/memefi-godmode/memefi.py", line 365, in main
    result = Check_user(index)
             ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/memefi-godmode/memefi.py", line 128, in Check_user
    access_token = fetch(index + 1)
                   ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/memefi-godmode/memefi.py", line 73, in fetch
    query_id = tg_web_data.split('query_id=', maxsplit=1)[1].split('&user', maxsplit=1)[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by ashtrobe** [comment]
issue with your query id
