### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xMacoy01** [ashtrobe/memefi-godmode#2]
Traceback (most recent call last):
  File "C:\Users\x\Desktop\memefi-godmode-main\memefi.py", line 582, in <module>
    main()
  File "C:\Users\x\Desktop\memefi-godmode-main\memefi.py", line 442, in main
    claim_combo(index, headers)
  File "C:\Users\x\Desktop\memefi-godmode-main\memefi.py", line 519, in claim_combo
    if response and 'data' in response and 'telegramGameProcessTapsBatch' in response['data']:
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
Press any key to continue . . .

**Comment by ashtrobe** [comment]
issue with the query id
